using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaVentaMusical.Models
{
    // Only keep the enum since it's not generated by EDMX
    public enum TipoPago { PayPal, TransferenciaBancaria, TarjetaCredito }
}