//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaVentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int UsuarioID { get; set; }
        public string Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public string Genero { get; set; }
        public string CorreoElectronico { get; set; }
        public string TipoTarjeta { get; set; }
        public decimal DineroDisponible { get; set; }
        public string NumeroTarjeta { get; set; }
        public int PerfilID { get; set; }
        public string IdentityUserID { get; set; }
    
        public virtual Perfiles Perfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
