//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaVentaMusical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int VentaID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string TipoPago { get; set; }
        public string NumeroTarjetaEnmascarado { get; set; }
        public string CodigoTarjeta { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal ComisionTarjeta { get; set; }
        public decimal Total { get; set; }
        public decimal DineroUtilizado { get; set; }
        public string NumeroFactura { get; set; }
        public bool EsReversada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
